### ISSUE TITLE
There is very less space between text and image in about.html page

### ISSUE THREAD

**Issue by vishal02527** [ChromeGaming/Physi-c-Tech#124]
### 🎮 feature Request

@thevirengarg your project is awesome but I got an issue that there is very less space between text and image in the about.html page. 

![Screenshot 2024-05-27 151549](https://github.com/GameSphere-MultiPlayer/Physi-c-Tech/assets/135222259/260f0401-2791-48c0-8896-baf2aec99970)

### Point down the features

I can maintain an appropriate space between the text and image so that it will be easy to the users to understand.

I want to fix this issue, please add labels on this issue and assign this issue to me.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by vishal02527** [comment]
@thevirengarg  please assign this issue to me

**Comment by kunwarnaunihalsingh** [comment]
hey, please assign this project to me since I believe that my skills in HTML, CSS and JS make me an ideal fit to contribute for your project.

**Comment by vishal02527** [comment]
@kunwarnaunihalsingh First see carefully, this issue has already been resolved and merged successfully.
