### ISSUE TITLE
[New Feature]: Navbar enhancement

### ISSUE THREAD

**Issue by triggereddown** [ChromeGaming/Physi-c-Tech#13]
### 🎮 feature Request

Adding Navbar
Would like to add a Navbar which will inorporate the current Home ,past play wins icons in it , making the experience for the UI better.

### Point down the features

feature points
1. Addition of Navbar
2. Icon on top will appear clearly
3. Increase in web-app appeal

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Durgesh4993** [comment]
@triggereddown Could you please explain more what you want to do, if possible you can also add screenshot.

**Comment by shristipandey128** [comment]
Please assign me this issue

**Comment by duttayugapriya** [comment]
Sir please assign me this issue

**Comment by Yuvraj960** [comment]
@Durgesh4993 Please assign this issue to me under GSSoC24
