### ISSUE TITLE
[Bug]: About button not appearing on home page even after scrolling down.

### ISSUE THREAD

**Issue by yeolesanskruti** [ChromeGaming/Physi-c-Tech#148]
### Give a brief about the bug ✍️

About Button not seen after scrolling down.

![Screenshot 2024-05-30 234819](https://github.com/ChromeGaming/Physi-c-Tech/assets/129084275/63c71593-b2e8-4836-99f1-a1ec1c3add31)

### What is the expected behavior? 🤔

Like the other three buttons 'ABOUT' button should also appear as per the HTML code file.

### Provide step by step information reproduce the bug 📄

I can resolve this issue by making changes to the below code. I am well versed in HTML, CSS, and JS and great at learning more.

![Screenshot 2024-05-30 235158](https://github.com/ChromeGaming/Physi-c-Tech/assets/129084275/c1bb9438-2ed6-4159-a9f7-690639bdcf86)

Please assign me this issue.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by yeolesanskruti** [comment]
@thevirengarg, I would like to work on this issue. Please assign me this under GSSoC'24.

**Comment by Abdul-momin24** [comment]
can you assign me this issue
