### ISSUE TITLE
[Bug]: >>>>Head is printed on the top of the page

### ISSUE THREAD

**Issue by Amruta7203** [ChromeGaming/Physi-c-Tech#153]
### Give a brief about the bug ✍️

>>>>>>head is getting displayed on the page of the website.
This is confusing for the users.

### What is the expected behavior? 🤔

![image](https://github.com/ChromeGaming/Physi-c-Tech/assets/116087736/f2fe2595-8266-447c-95b3-dff53b640378)

### Provide step by step information reproduce the bug 📄

Removing the unnecessary print. 

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by VaibhavYT** [comment]
This bug is fixed by me have a look on PR number #157
