### ISSUE TITLE
[New Feature]:  Enhancing a head part at top left corner  into the button.

### ISSUE THREAD

**Issue by josum06** [ChromeGaming/Physi-c-Tech#155]
### 🎮 feature Request

feature logic and basic description:

<img width="666" alt="physc game" src="https://github.com/ChromeGaming/Physi-c-Tech/assets/136955127/1501aef9-2ebd-46c7-aeb3-41db649834ae">

Replace text with a visible button for easy instruction access, improving navigation. This enhances user experience by simplifying the process and increasing engagement.

### Point down the features

feature points:-
1 **Intuitive Navigation:** Replace text with a clear, user-friendly button, aiding new users in finding instructions effortlessly.
2 **Enhanced Visibility:** By prominently featuring the button, we ensure it catches the eye, guiding users seamlessly to the instruction page.
3 **Improved User Experience:** Simplifying navigation with intuitive design elements enhances user satisfaction .

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by komalverma04** [comment]
@josum06 I would like to work on this issue, should i start?

**Comment by josum06** [comment]
@thevirengarg should i start working on this issue ?
