### ISSUE TITLE
[Bug]: Changing image of home page in about page

### ISSUE THREAD

**Issue by SalehaTabassum** [ChromeGaming/Physi-c-Tech#156]
### Give a brief about the bug ✍️

In the about page there is an image of old home page.
![Screenshot 2024-06-01 215551](https://github.com/ChromeGaming/Physi-c-Tech/assets/169278740/e5da5813-5b8b-47c3-a22a-da64a03859b2)

### What is the expected behavior? 🤔

I want to add  the new home page image.

@Durgesh4993 please assign this issue to me under GSSOC 2024 and add appropriate labels to it.

### Provide step by step information reproduce the bug 📄

Description

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by kunwarnaunihalsingh** [comment]
hey, please assign this project to me since I believe that my skills in HTML, CSS and JS make me an ideal fit to contribute for your project.
