### ISSUE TITLE
[Bug]: Home page not responsive for mobile

### ISSUE THREAD

**Issue by SalehaTabassum** [ChromeGaming/Physi-c-Tech#159]
### Give a brief about the bug ✍️

Hello @Durgesh4993 
The home page is not responsive .
![Screenshot 2024-06-02 233014](https://github.com/ChromeGaming/Physi-c-Tech/assets/169278740/b7f73a1f-8825-4b99-8438-6a111d1a8224)

it looks like this in mobile:
![Screenshot_2024-06-02-23-30-32-77_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/ChromeGaming/Physi-c-Tech/assets/169278740/13b82453-60b3-4508-b2f0-cf06e3e138c8)

so please assign this issue to me under GSSOC 2024 and add appropriate labels to it.

### What is the expected behavior? 🤔

Description

### Provide step by step information reproduce the bug 📄

Description

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by SalehaTabassum** [comment]
@thevirengarg could you please add the level labels

**Comment by thevirengarg** [comment]
@SalehaTabassum I will add it to the PR. There is no need for an issue to have a level tag.
