### ISSUE TITLE
[Enhancement]: added hover effect on this button

### ISSUE THREAD

**Issue by shuhaki** [ChromeGaming/Physi-c-Tech#184]
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

Game enhancement

### Describe the solution you'd like

Solution steps
<img width="108" alt="Screenshot 2024-06-08 at 4 00 04 AM" src="https://github.com/ChromeGaming/Physi-c-Tech/assets/145912232/d18f03f7-adfc-4d5e-ade9-85d6a0e76921">

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by thevirengarg** [comment]
@Dont create two PRs for the same issue, Do all the changes of hover effect in one.
