### ISSUE TITLE
[New Feature]:  adding animation to home page

### ISSUE THREAD

**Issue by dnyandeepchute** [ChromeGaming/Physi-c-Tech#202]
### 🎮 feature Request

adding animation to home page to make it attractive.

### Point down the features

snow fall animation

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by dnyandeepchute** [comment]
please assign this to me, thank you.

**Comment by ankitmodanwall** [comment]
hey could you share ss there.?
