### ISSUE TITLE
[New Feature]: Adding a 404-Error Page

### ISSUE THREAD

**Issue by AkshitGarg24** [ChromeGaming/Physi-c-Tech#204]
### 🎮 feature Request

To ensure a positive user experience, a custom 404 error page should be created and displayed when a user navigates to a non-existent or incorrect web address. This page should provide a friendly message and useful navigation links. Currently, it is showing like this ->

![Screenshot 2024-06-17 000341](https://github.com/ChromeGaming/Physi-c-Tech/assets/153659573/efb17e6c-0e1a-4895-83ff-9e05348b403e)

### Point down the features

I already mentioned above.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Anup2601** [comment]
I am GSSOC24 Contributor
Please assign me, I would like to work on it
