### ISSUE TITLE
No Scroll effect in the Home page of the game[Bug]: 

### ISSUE THREAD

**Issue by VinayJangotra** [ChromeGaming/Physi-c-Tech#206]
### Give a brief about the bug ✍️

Description
![Screenshot 2024-06-17 231730](https://github.com/ChromeGaming/Physi-c-Tech/assets/109384165/34a9653e-6120-49d2-ae52-97df6ec5fa8e)

In this page the screen is look like , It just freezed ,I cannot see the option after the sound on

### What is the expected behavior? 🤔

It must scroll down and show the fourth option

### Provide step by step information reproduce the bug 📄

I can fix this bug by adding the scroll effect and make the page responsive

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by VinayJangotra** [comment]
I want to work on it assign me the issue

**Comment by thevirengarg** [comment]
@VinayJangotra Explain the issue in detail

**Comment by VinayJangotra** [comment]
@thevirengarg  when i open this application in my browser (brave) the 4 th option in the home page which is About is not showing so, there was a need of a scroll effect in the home page , so I fix this issue and create the pull request ,please merge it I fix this issue
