### ISSUE TITLE
Reorganise the repository and make different files for js, css and img files so that it becomes more accessible and visually good

### ISSUE THREAD

**Issue by partha120804** [ChromeGaming/Physi-c-Tech#211]
### 🎮 feature Request

Make different folders for img/png, css, and js files and change all their references accordingly

### Point down the features

feature points:

Becomes easy to access

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by avinash-24-aptrix** [comment]
Assign me i can properly make  structure fot this project
