### ISSUE TITLE
[New Feature]: improving the buttons 

### ISSUE THREAD

**Issue by SalehaTabassum** [ChromeGaming/Physi-c-Tech#22]
### 🎮 feature Request

![Screenshot 2024-05-11 233047](https://github.com/GameSphere-MultiPlayer/Physi-c-Tech/assets/169278740/96c6e011-b6f1-43b1-b2d7-cb458ab71965)

As we can see that the buttons look so dull and not much attractive .I would like to enhance these buttons and add hover effects so that it looks attractive.

![Screenshot 2024-05-11 232948](https://github.com/GameSphere-MultiPlayer/Physi-c-Tech/assets/169278740/913b3ca5-2cf5-45da-9802-100620635c75)
i am here adding a sample picture about how i want to design the buttons .

@Durgesh4993 sir please assign this issue to me under gssoc 2024 .it would give me pleasure to work over it

### Point down the features

feature points

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Durgesh4993** [comment]
If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created seprate chennals for all projects...

Thank you :)

**Comment by vaishnavip27** [comment]
Hey, I can wrok on this issue as I have goof experince in designing and building buttons. Please assign me this issue. Looking forward for the approval
