### ISSUE TITLE
Feedback Form Integration and Confirmation Message Issue 

### ISSUE THREAD

**Issue by TBorundia** [ChromeGaming/Physi-c-Tech#221]
### 🎮 feature Request

The feedback form on our website is currently not linked properly to the website , there is no option to navigate to the form page.
So the button is required to navigate.
Users must encounter a message when trying to submit the form, so that must be added in the feature.

### Point down the features

Form Integration: Ensure that the feedback form is correctly linked to the website's .
Confirmation Message: Display a confirmation message to users after successful form submission.

![image](https://github.com/ChromeGaming/Physi-c-Tech/assets/168854094/22bdd054-7eae-4880-81b7-67cbb8c1cf0c)

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by TBorundia** [comment]
@Durgesh4993 @thevirengarg Sir please assign this issue to me under GSSoC'24.

**Comment by thevirengarg** [comment]
@TBorundia What do you mean by not linked properly?

**Comment by TBorundia** [comment]
@thevirengarg Sir, there is no option in website to navigate to feedback form page.
