### ISSUE TITLE
Adding a back to home option in feedback form

### ISSUE THREAD

**Issue by Khushipawar37** [ChromeGaming/Physi-c-Tech#229]
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

Game enhancement- If clicked on feedback form by mistake, there must be an option to return back to home instead of refreshing the whole web page again

### Describe the solution you'd like

Solution steps

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Akuu-27** [comment]
I would like to work on this task .

**Comment by Khushipawar37** [comment]
I am working on this @thevirengarg, kindly attach appropriate label for the level too.
