### ISSUE TITLE
[New Feature]: Adding Contributors page

### ISSUE THREAD

**Issue by TBorundia** [ChromeGaming/Physi-c-Tech#258]
### 🎮 feature Request

I can add the option to navigate contributor page.
I will show the github profile of all the contributors worked for the project.
I will ensure to make the page UI similar to the theme and also responsive for all screens.
It will directly fetch the data from the repository.

![image](https://github.com/ChromeGaming/Physi-c-Tech/assets/168854094/672cae10-fef8-4b99-87cb-e9b89f724198) how it will help for website

It will show,
Transparency: It shows transparency in the project's development and highlights the collaborative effort behind it.
Engagement: It helps build a community by encouraging more people to contribute and get involved.
Networking: It provides an opportunity for users to connect with contributors, potentially leading to more collaboration and support.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by TBorundia** [comment]
@Durgesh4993 @thevirengarg Sir,
Please assign this issue to me under GSSoC'24. Thank you!

**Comment by thevirengarg** [comment]
@TBorundia Don't add contributors page on the website, else add it in the README.md
