### ISSUE TITLE
[Enhancement]: Homepage button Enhancement 

### ISSUE THREAD

**Issue by prachi-kurmi** [ChromeGaming/Physi-c-Tech#42]
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

Game enhancement
![Screenshot 2024-05-13 073937](https://github.com/GameSphere-MultiPlayer/Physi-c-Tech/assets/125259987/e86b1577-5a2a-457c-b65b-348265b09ee1)

I want to add buttons to the website. When visitors land on the website, they should see buttons labeled "Continue" "New Game" and "Sound On/Off". This will make navigation and understanding easier for users.

### Describe the solution you'd like

Solution steps:
Create visually distinct buttons for "Continue' , "New Game" and "Sound On/Off" using clear labels.
Ensure the buttons are large enough to be easily clickable and stand out from other page elements.
When someone hovers over the buttons, make them change a little, like color or size.
Use HTML and CSS to create the buttons and style them.

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by prachi-kurmi** [comment]
@Durgesh4993 please assign me this issue under GSSoC'24 and add necessary labels.

**Comment by vardhini3103** [comment]
@Durgesh4993 I would like to work on this issue. Please assign it to me.

**Comment by Durgesh4993** [comment]
@prachi-kurmi Could you please explain more what you want to do, if possible you can also add screenshot.

**Comment by Durgesh4993** [comment]
If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created seprate chennals for all projects...

Thank you :)

**Comment by prachi-kurmi** [comment]
![Screenshot 2024-05-13 073937](https://github.com/GameSphere-MultiPlayer/Physi-c-Tech/assets/125259987/c3cb138e-9d4d-467a-a5f0-278545134237)

As you can see in the screenshot above, there is simply written text for 'New Game,' 'Continue,' and 'Sound On/Off.' What if I add button labels for 'New Game,' 'Continue,' and 'Sound On/Off'? It would become more user-friendly.

**Comment by NeerajaGurram** [comment]
I would like to work on this please assign me this under GSSoC'24 

To solve this I would like to use css and html and style them in an attractive manner
![IMG_20240514_142653.jpg](https://github.com/GameSphere-MultiPlayer/Physi-c-Tech/assets/152693538/36ae1632-727a-4e6b-8594-2bc4fbd407e8)



The above image is provided for Example 
A button style is given for the names on home page and effects are given to themwhen hovered

**Comment by KomalSrivastava** [comment]
@thevirengarg I am confident that, if assigned this task, I will complete it promptly and to a high standard. My goal is to create a visually appealing and user-friendly About page that accurately represents our project and engages our audience. I am excited to contribute to this project under GSSoC and make a positive impact on our website.

I will use my skills in HTML, CSS, and JavaScript to create a responsive and accessible About page that meets the needs of our users. I will also ensure that the page is optimized for search engines and follows best practices for web development.

I am confident that my contributions will help to improve the overall user experience of our website and make it a valuable resource for our audience.

**Comment by KomalSrivastava** [comment]
@thevirengarg I am confident that, if assigned this task, I will complete it promptly and to a high standard. My goal is to create a visually appealing and user-friendly About page that accurately represents our project and engages our audience. I am excited to contribute to this project under GSSoC and make a positive impact on our website.

I will use my skills in HTML, CSS, and JavaScript to create a responsive and accessible Home page that meets the needs of our users. I will also ensure that the page is optimized for search engines and follows best practices for web development.

I am confident that my contributions will help to improve the overall user experience of our website and make it a valuable resource for our audience.

**Comment by thevirengarg** [comment]
@KomalSrivastava There is a process of contributing to a open-source project: 1) You need to identify an issue or suggest some improvement in the codebase based on your tech-stack,  if project maintainer feels that it is a genuine issue. he/she will assign you the issue. Make sure that the improvement you are proposing is not already assigned to someone else. You can go to issues tab and see all the issues created and assigned. 
2) After you get an issue assigned, you can start working on it. If you need any guidance or face an issue while working on the issue you can contact the maintainers they will help you. 
3) After you solve the issue, create a pull request, the maintainer will review the PR and add labels to the PR accordingly. 

There are some points to keep in mind while making a open-source contribution:
1) Don't create a PR before you get the issue assigned, if you feel the process is slow you can work on 2-3 projects simultaneously. 
2) Don't comment on closed issues or ask for reopening them. 
3) Don't ask to get an issue assigned which has been already been assigned to someone else. 
4) Don't create a PR for someone else's issue.
5) When you are putting forward a proposal of an issue don't write long paragraphs regarding it, always prefer writing in points and in a concise way.

**Comment by thevirengarg** [comment]
@KomalSrivastava If you still have doubts, you can reach out to me on LinkedIn or discord. My profile - https://www.linkedin.com/in/thevirengarg/
